from typing import TypedDict, List, Annotated
import operator

class AgentState(TypedDict):
    """
    The state of the agent swarm.
    
    Attributes:
        goal (str): The primary objective provided by the user.
        plan (List[str]): The sequence of tasks generated by the Manager.
        research_notes (Annotated[List[str], operator.add]): Accumulated data from the Researcher.
        draft (str): The current version of the content produced by the Writer.
        revision_notes (str): Feedback/Instructions from the Reviewer.
        iterations (int): Counter to prevent infinite loops.
        next_agent (str): Routing information for the Manager.
    """
    goal: str
    plan: List[str]
    research_notes: Annotated[List[str], operator.add]
    draft: str
    revision_notes: str
    iterations: int
    next_agent: str
